### ISSUE TITLE
Translation Standards and Contribution Guidelines

### ISSUE THREAD

**Issue by Peruibeloko** [javascript-tutorial/pt.javascript.info#431]
@nazarepiedady @odsantos @jonnathan-ls

It has come to my attention that the lack of a common basis on what to translate and how is creating a couple of problems in recent contributions.

This forum should solve this issue with two key artifacts:
- A guide for translation standards, by which all reviews and translations should abide by
- Approval by majority on the proposed #428 Contribution Guidelines, with any additions deemed necessary.

I'd like to kick off the discussion by pointing out recent discussions I've had with Nazaré, regarding competing translation standards, which got a bit out of hand. The relevant issues are #428 and #415.

- What should we keep in English for familiarity sake?
- What English words with no clear Portuguese equivalent should we try and translate?
- Are there any guidelines we should establish regarding expressing our personal preferences regarding translations? How should they play into the translation itself?
- Should our comments and reviews be in English or Portuguese?

**Comment by Peruibeloko** [comment]
I'd also ask for some attention to this discussion because I'm starting to feel a bit demotivated by the aggressive discussions and the lack of a clear direction to follow, and I wouldn't like for that to be the case for other contributors or maintainers :/

**Comment by danilolmc** [comment]
Great @Peruibeloko, sometimes I don't know what tone to use in translations, leading increasing review time in greater articles.

**Comment by odsantos** [comment]
@Peruibeloko as far as I see you're doing a good work and probably it would be beneficial if continued.

As far as I remember, variable names and a few other words should not be translated, such as 'Importance' in exercises and in general those at the start code block examples beginning with three backtiks.

Probably, almost all should be translated, unless easier to understand in English, such as 'string' instead of 'cadeia de caracteres', for instance.

Perhaps, comments should be in English. 
@iliakan apparently is the site owner and he does not speak Portuguese, so it might probably not be polite to leave him without a clue of what is being discussed in any section related to it.

 Looking forward to continue reading from you.
Thank you.

**Comment by Peruibeloko** [comment]
@odsantos @nazarepiedady Makes sense, so Brazilian Portuguese it is, I'll add that to the contribution guidelines.

> Probably, almost all should be translated, unless easier to understand in English, such as 'string' instead of 'cadeia de caracteres', for instance.

@odsantos so things like "website", "string", "link", are better kept in English, which I agree.
